/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package PrintScript

import org.junit.jupiter.api.Test

class AppSuite{
  @Test
  def appHasAGreeting(): Unit = {
    assert(App.greeting() != null)
  }
}
